pipeline{
    agent any

    tools{
        maven 'maven 3.6.1'
    }

    stages{
        stage('build'){
            steps{
                echo 'build stage'
                dir('open-culture-backend'){
                    sh 'mvnw compile'
                }
                
            }
        }

        stage('test'){
            steps{
                echo 'test stage'
                dir('open-culture-backend'){
                    sh 'mvnw clean test'
                }                
            }
        }

        stage('package'){
            steps{
                echo 'package stage'
                dir('open-culture-backend'){
                    sh 'mvnw package -DskipTests'
                }
            }
        }
    }
}